apiVersion: v2
name: pod-log-service
description: A Helm chart for a Pod Log Service
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: nats
    version: 1.1.4
    repository: https://github.com/nats-io/k8s/tree/main/helm
