# Default values for log-service
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  prefix: pod-log-service
  repository: pod-log-service
  tag: v0.8
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

nats:
  config:
    jetstream:
      enabled: true