apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-log-service
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-log-service
rules:
- apiGroups: ["apps", "extensions", ""]
  resources: ["pods", "namespaces", "services", "pods/log"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-log-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-log-service
subjects:
- kind: ServiceAccount
  name: pod-log-service
  namespace: {{ .Release.Namespace }}